# Generated by Django 6.0.6 on 2026-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Pièce'), ('metre', 'Mètre')], default='piece', help_text='Unité de vente (ex. tissu/bazin vendus au mètre)', max_length=10),
        ),
    ]
