# Generated by Copilot on 2026-07-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_seller_slug_blank"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Boutique publique à laquelle le produit est associé.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="sellers.shop",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_cover",
            field=models.BooleanField(default=False, help_text="Image principale de la galerie."),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
