# Generated by Django 6.0.7 on 2026-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_shop_and_productimage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "Rouge", "hex": "#FF0000", "stock": 10}, ...]'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, default='', help_text='Couleur associée (doit correspondre à un nom dans Product.colors)', max_length=50),
        ),
    ]
