# Generated by Django 6.0.7 on 2026-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_to_order',
            field=models.BooleanField(default=False, help_text='Produit fabriqué à la commande : pas de suivi de stock (ex. restauration).'),
        ),
    ]
