# Generated by Django 6.0.7 on 2026-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('PAID', 'Payant')], default='FREE', max_length=10),
        ),
    ]
