# Generated by Django 6.0.7 on 2026-07-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_add_plan_to_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='visible_on_main_store',
            field=models.BooleanField(default=True, help_text='Afficher les produits de cette boutique dans le catalogue, la recherche et la wishlist de la vitrine principale anifowoche.com'),
        ),
    ]
