# Generated by Django 6.1 on 2026-08-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_free_shops_hidden_from_main_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Gratuit'), ('PAID', 'Payant')], default='PAID', max_length=10)),
                ('amount_xof', models.PositiveIntegerField()),
                ('provider', models.CharField(choices=[('fedapay', 'FedaPay')], default='fedapay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('declined', 'Refusé'), ('canceled', 'Annulé'), ('failed', "Échec d'initialisation")], default='pending', max_length=20)),
                ('fedapay_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_url', models.URLField(blank=True)),
                ('last_webhook_payload', models.JSONField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
