# Generated by Django 6.1 on 2026-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='FREE', max_length=10),
        ),
        migrations.AlterField(
            model_name='sellersubscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='PRO', max_length=10),
        ),
    ]
