# Generated by Django 6.1 on 2026-08-13 13:49

from django.db import migrations


def migrate_paid_to_pro(apps, schema_editor):
    SellerProfile = apps.get_model("sellers", "SellerProfile")
    SellerProfile.objects.filter(plan="PAID").update(plan="PRO")


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0007_alter_sellerprofile_plan_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_paid_to_pro, migrations.RunPython.noop),
    ]
