# Generated by Django 6.1 on 2026-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_add_is_official_to_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubscription',
            name='last_expiry_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
