# Generated by Django 6.1 on 2026-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_official_shop_business_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Boutique officielle anifowoche.com : aucune limite de plan. Plusieurs boutiques peuvent être officielles.'),
        ),
    ]
