# Generated by Django 6.1 on 2026-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_alter_shop_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubscription',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
