# Generated by Django 6.1 on 2026-09-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0013_sellersubscription_cancel_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubscription',
            name='is_upgrade',
            field=models.BooleanField(default=False, help_text='Upgrade au prorata : conserve la fin de période en cours.'),
        ),
    ]
