# Generated by Django 6.0.6 on 2026-07-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fedapay', 'FedaPay')], default='fedapay', max_length=20)),
                ('method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('card', 'Carte bancaire')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('declined', 'Refusé'), ('canceled', 'Annulé'), ('failed', "Échec d'initialisation")], default='pending', max_length=20)),
                ('amount_xof', models.PositiveIntegerField()),
                ('fedapay_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_url', models.URLField(blank=True)),
                ('last_webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
