# Generated by Django 6.0.6 on 2026-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_payment_enabled', models.BooleanField(default=True, help_text='Si désactivé, aucun paiement en ligne ne peut être initié (repli commande à la livraison).')),
                ('mtn_enabled', models.BooleanField(default=True, help_text='Autoriser le paiement par MTN Mobile Money.')),
                ('moov_enabled', models.BooleanField(default=True, help_text='Autoriser le paiement par Moov Money.')),
                ('card_enabled', models.BooleanField(default=True, help_text='Autoriser le paiement par carte bancaire.')),
            ],
            options={
                'verbose_name': 'Réglages paiement',
                'verbose_name_plural': 'Réglages paiement',
            },
        ),
    ]
