# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("fedapay", "FedaPay"),
                    ("cash_on_delivery", "Paiement à la livraison"),
                ],
                default="fedapay",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("mtn", "MTN Mobile Money"),
                    ("moov", "Moov Money"),
                    ("card", "Carte bancaire"),
                    ("cash_on_delivery", "Paiement à la livraison"),
                ],
                max_length=20,
            ),
        ),
    ]
