# Generated by Django 6.0.6 on 2026-07-04 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_admin_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Si activé, plus aucune nouvelle commande ne peut être passée (boutique en pause).')),
            ],
            options={
                'verbose_name': 'Réglages boutique',
                'verbose_name_plural': 'Réglages boutique',
            },
        ),
        migrations.CreateModel(
            name='SettingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(choices=[('maintenance_mode', 'Mode maintenance boutique'), ('online_payment_enabled', 'Paiement en ligne (global)'), ('payment_method_mtn', 'Paiement MTN Mobile Money'), ('payment_method_moov', 'Paiement Moov Money'), ('payment_method_card', 'Paiement carte bancaire')], max_length=30)),
                ('target_value', models.BooleanField(help_text='Valeur demandée : coché = activer, décoché = désactiver.')),
                ('reason', models.TextField(help_text='Justification de la demande (obligatoire).')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=10)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de changement de réglage',
                'verbose_name_plural': 'Demandes de changement de réglage',
                'ordering': ['-created_at'],
            },
        ),
    ]
