# Generated by Django 6.0.6 on 2026-07-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Héro / carrousel'), ('trust', 'Arguments de confiance'), ('categories', 'Catégories'), ('featured', 'Produits mis en avant')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Section d'accueil",
                'verbose_name_plural': "Sections d'accueil",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ANIFOWOCHE', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='appearance/')),
                ('color_brand', models.CharField(default='#c99f08', help_text='Couleur principale de la marque, au format hex #rrggbb.', max_length=7)),
                ('color_brand_dark', models.CharField(default='#8b6604', help_text='Variante foncée de la couleur de marque, au format hex #rrggbb.', max_length=7)),
                ('color_brand_medium', models.CharField(default='#a67c06', help_text='Variante intermédiaire de la couleur de marque, au format hex #rrggbb.', max_length=7)),
                ('color_brand_light', models.CharField(default='#fef3c7', help_text='Variante claire de la couleur de marque, au format hex #rrggbb.', max_length=7)),
                ('color_brand_pale', models.CharField(default='#fffaf0', help_text='Variante très pâle de la couleur de marque, au format hex #rrggbb.', max_length=7)),
                ('hero_eyebrow', models.CharField(blank=True, default='Collection Cotonou', max_length=100)),
                ('hero_title', models.CharField(blank=True, default='Tissus, vêtements & accessoires', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Des pièces sélectionnées pour le quotidien, les cérémonies et les sorties, avec paiement mobile money et livraison à domicile sur Cotonou.', max_length=500)),
                ('trust_arguments', models.JSONField(blank=True, default=list, help_text="Liste de textes courts (arguments de confiance), ex. ['Livraison sous 48h', 'Paiement MTN, Moov, Visa'].")),
            ],
            options={
                'verbose_name': 'Apparence du site',
                'verbose_name_plural': 'Apparence du site',
            },
        ),
    ]
