# Generated by Django 6.0.7 on 2026-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('trust', 'Arguments de confiance'), ('categories', 'Catégories'), ('featured', 'Produits mis en avant')], max_length=20, unique=True),
        ),
    ]
