# Generated by Django 6.0.7 on 2026-08-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_delete_hero_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetheme',
            name='hero_eyebrow',
        ),
        migrations.RemoveField(
            model_name='sitetheme',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitetheme',
            name='hero_title',
        ),
    ]
