# Generated by Django 6.1 on 2026-08-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_remove_sitetheme_hero_eyebrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list, help_text='Liste d\'objets {"label", "url"}')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloc footer',
                'verbose_name_plural': 'Blocs footer',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Élément de menu',
                'verbose_name_plural': 'Éléments de menu',
                'ordering': ['order', 'id'],
            },
        ),
    ]
