# Generated by Django 6.1 on 2026-09-19 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_footerblock_menuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée')], default='draft', max_length=20)),
                ('theme', models.JSONField(default=dict)),
                ('sections', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearance_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Version d'apparence",
                'verbose_name_plural': "Versions d'apparence",
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
