# Generated by Django 6.0.6 on 2026-07-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_xof',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
