# Generated by Django 6.0.7 on 2026-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancellation_reason_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_hex',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
