# Generated by Django 6.0.7 on 2026-07-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_color_hex_orderitem_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list, help_text='[{"group_id": 1, "group_name": "Accompagnement", "option_id": 5, "option_name": "Frites", "price_xof": 500}, ...]'),
        ),
    ]
