# Generated by Django 6.1 on 2026-08-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_increase_coordinate_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Livraison'), ('pickup', 'Retrait chez le vendeur')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
