# Generated by Django 6.1 on 2026-09-18 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_delivery_method_alter_order_address'),
        ('sellers', '0014_sellersubscription_is_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('items', models.JSONField(blank=True, default=list, help_text='[{"id":1,"slug":"pagne","name":"Pagne","image":"/media/...","price_xof":2000,"quantity":2,"color_name":"Rouge","color_hex":"#FF0000","selected_options":[...],"delivery_method":"delivery"}, ...]')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('converted', 'Converti'), ('expired', 'Expiré')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abandoned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, help_text='Boutique concernée (isole les paniers ANIF Seller par boutique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_carts', to='sellers.shop')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', 'abandoned_at'], name='abandoned_status_aband_idx')],
            },
        ),
    ]
