# Generated by Django 6.0.6 on 2026-07-01 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Demandé'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('refunded', 'Remboursé')], default='requested', max_length=20)),
                ('refund_amount_xof', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'Retour',
                'verbose_name_plural': 'Retours',
                'ordering': ['-created_at'],
            },
        ),
    ]
