# Generated by Django 6.0.6 on 2026-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_confirmation', 'Confirmation de commande'), ('delivery_in_transit', 'Commande en route'), ('delivery_confirmed', 'Livraison confirmée'), ('invoice', 'Facture'), ('account_created', 'Création de compte')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
