# Generated by Django 6.0.6 on 2026-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_recipient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=False, help_text="Activer l'envoi réel de notifications WhatsApp (nécessite une vraie clé WhatsApp Business API).")),
                ('sms_enabled', models.BooleanField(default=False, help_text="Activer l'envoi réel de notifications SMS (nécessite un fournisseur SMS configuré).")),
            ],
            options={
                'verbose_name': 'Réglages notifications',
                'verbose_name_plural': 'Réglages notifications',
            },
        ),
    ]
