# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackofficeNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("approval_required", "Validation requise"),
                            ("provider_error", "Erreur fournisseur"),
                            ("configuration", "Problème de configuration"),
                            ("system_error", "Erreur système"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Attention"), ("error", "Erreur")],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Alerte backoffice",
                "verbose_name_plural": "Alertes backoffice",
                "ordering": ["-created_at"],
            },
        ),
    ]
