# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_backofficenotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Confirmation de commande"),
                    ("delivery_in_transit", "Commande en route"),
                    ("delivery_confirmed", "Livraison confirmée"),
                    ("invoice", "Facture"),
                    ("account_created", "Création de compte"),
                    ("setting_change_requested", "Demande de changement de réglage"),
                ],
                max_length=30,
            ),
        ),
    ]
