# Generated by Django 6.0.6 on 2026-07-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backofficenotification',
            name='kind',
            field=models.CharField(choices=[('approval_required', 'Validation requise'), ('provider_error', 'Erreur fournisseur'), ('configuration', 'Problème de configuration'), ('system_error', 'Erreur système'), ('payment_failed', 'Paiement échoué')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_confirmation', 'Confirmation de commande'), ('delivery_in_transit', 'Commande en route'), ('delivery_confirmed', 'Livraison confirmée'), ('invoice', 'Facture'), ('account_created', 'Création de compte'), ('setting_change_requested', 'Demande de changement de réglage'), ('payment_retry', 'Relance de paiement')], max_length=30),
        ),
    ]
