# Generated by Django 6.0.7 on 2026-07-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_backofficenotification_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_confirmation', 'Confirmation de commande'), ('order_cancelled', 'Annulation de commande'), ('delivery_in_transit', 'Commande en route'), ('delivery_confirmed', 'Livraison confirmée'), ('invoice', 'Facture'), ('account_created', 'Création de compte'), ('setting_change_requested', 'Demande de changement de réglage'), ('payment_retry', 'Relance de paiement')], max_length=30),
        ),
    ]
