# Generated by Django 6.0.7 on 2026-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='backofficenotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backofficenotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
