# Generated by Django 6.1 on 2026-08-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backofficenotification',
            name='kind',
            field=models.CharField(choices=[('approval_required', 'Validation requise'), ('provider_error', 'Erreur fournisseur'), ('configuration', 'Problème de configuration'), ('system_error', 'Erreur système'), ('payment_failed', 'Paiement échoué'), ('sensitive_action', 'Action sensible')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_confirmation', 'Confirmation de commande'), ('order_cancelled', 'Annulation de commande'), ('delivery_in_transit', 'Commande en route'), ('delivery_confirmed', 'Livraison confirmée'), ('invoice', 'Facture'), ('account_created', 'Création de compte'), ('setting_change_requested', 'Demande de changement de réglage'), ('payment_retry', 'Relance de paiement'), ('subscription_expiring', 'Abonnement bientôt expiré'), ('sensitive_action', 'Action sensible')], max_length=30),
        ),
    ]
