# Generated by Django 6.1 on 2026-08-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_add_sensitive_action_event'),
        ('sellers', '0010_sellersubscription_last_expiry_reminder_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'Nouvelle commande'), ('order_cancelled', 'Commande annulée'), ('low_stock', 'Stock faible'), ('plan_expiring', 'Abonnement bientôt expiré'), ('broadcast', 'Message ANIFOWOCHE'), ('account', 'Compte'), ('system', 'Système')], default='broadcast', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sellers.sellerprofile')),
            ],
            options={
                'verbose_name': 'Notification vendeur',
                'verbose_name_plural': 'Notifications vendeur',
                'ordering': ['-created_at'],
            },
        ),
    ]
