# Generated by Django 6.1 on 2026-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_add_subscription_downgraded_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_confirmation', 'Confirmation de commande'), ('order_cancelled', 'Annulation de commande'), ('delivery_in_transit', 'Commande en route'), ('delivery_confirmed', 'Livraison confirmée'), ('invoice', 'Facture'), ('account_created', 'Création de compte'), ('setting_change_requested', 'Demande de changement de réglage'), ('payment_retry', 'Relance de paiement'), ('subscription_expiring', 'Abonnement bientôt expiré'), ('subscription_downgraded', 'Abonnement expiré (plan FREE)'), ('subscription_canceled', 'Abonnement résilié'), ('sensitive_action', 'Action sensible')], max_length=30),
        ),
    ]
